/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Fichas.Ficha;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author Leovavi
 */
public final class Game extends javax.swing.JPanel {
    Tablero tab = new Tablero();
    BufferedImage bi;
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        setTableroPanel(tab);
        userLoggedLabel.setText(Menu.userLogged);
        userLogged2Label.setText(Menu.userLogged2);
    }

    public void setTableroPanel(JPanel panel){
        tablero.removeAll();
        tablero.add(panel);
        tablero.repaint();
        tablero.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new javax.swing.JPanel();
        btnSaveQuit = new javax.swing.JButton();
        btnSurrender = new javax.swing.JButton();
        userLogged2Label = new javax.swing.JLabel();
        userLoggedLabel = new javax.swing.JLabel();
        MainLabel = new javax.swing.JLabel();

        setLayout(null);

        tablero.setLayout(null);
        add(tablero);
        tablero.setBounds(325, 30, 540, 600);

        btnSaveQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saveQuit.png"))); // NOI18N
        btnSaveQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQuitActionPerformed(evt);
            }
        });
        add(btnSaveQuit);
        btnSaveQuit.setBounds(20, 590, 200, 40);

        btnSurrender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/surrender.png"))); // NOI18N
        btnSurrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurrenderActionPerformed(evt);
            }
        });
        add(btnSurrender);
        btnSurrender.setBounds(20, 530, 200, 40);

        userLogged2Label.setFont(new java.awt.Font("Chinese Takeaway", 2, 18)); // NOI18N
        userLogged2Label.setText("User Logged 2");
        add(userLogged2Label);
        userLogged2Label.setBounds(940, 40, 180, 40);

        userLoggedLabel.setFont(new java.awt.Font("Chinese Takeaway", 2, 18)); // NOI18N
        userLoggedLabel.setText("User Logged");
        add(userLoggedLabel);
        userLoggedLabel.setBounds(40, 40, 180, 40);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/background.png"))); // NOI18N
        add(MainLabel);
        MainLabel.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSurrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurrenderActionPerformed
        Menu.PL.surrender(tab.t);
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnSurrenderActionPerformed

    private void btnSaveQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQuitActionPerformed
        //Aunque por los momentos solo se sale de la pantalla
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnSaveQuitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnSaveQuit;
    private javax.swing.JButton btnSurrender;
    private javax.swing.JPanel tablero;
    private javax.swing.JLabel userLogged2Label;
    private javax.swing.JLabel userLoggedLabel;
    // End of variables declaration//GEN-END:variables
}
