/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.util.NoSuchElementException;

/**
 *
 * @author Leovavi
 */
public class JugarXiangqi extends javax.swing.JPanel {

    /**
     * Creates new form JugarXiangqi
     */
    public JugarXiangqi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevaPartida = new javax.swing.JButton();
        btnCargarPartida = new javax.swing.JButton();
        btnEliminarPartida = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        MainLabel = new javax.swing.JLabel();

        setLayout(null);

        btnNuevaPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPartidaActionPerformed(evt);
            }
        });
        add(btnNuevaPartida);
        btnNuevaPartida.setBounds(430, 290, 300, 60);

        btnCargarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargar.png"))); // NOI18N
        btnCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPartidaActionPerformed(evt);
            }
        });
        add(btnCargarPartida);
        btnCargarPartida.setBounds(430, 390, 300, 60);

        btnEliminarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPartidaActionPerformed(evt);
            }
        });
        add(btnEliminarPartida);
        btnEliminarPartida.setBounds(430, 490, 300, 60);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(933, 603, 200, 40);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainBackground.png"))); // NOI18N
        add(MainLabel);
        MainLabel.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        if(Menu.ul.users.size()>1)
            Menu.menu.setPanel(new PlayersAvailable());
        else
            Menu.menu.showMessage("No Players Available");
    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
        Menu.menu.showMessage("PROXIMAMENTE ESTARA DISPONIBLE");
        //Menu.menu.setPanel(new LoadGame());
    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    private void btnEliminarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPartidaActionPerformed
        Menu.menu.showMessage("PROXIMAMENTE ESTARA DISPONIBLE");
        //Menu.menu.setPanel(new DeleteGame());
    }//GEN-LAST:event_btnEliminarPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarPartida;
    private javax.swing.JButton btnNuevaPartida;
    // End of variables declaration//GEN-END:variables
}
