package Visual;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class MenuInicio extends javax.swing.JPanel {
    /**
     * Creates new form MenuInicio
     */
    
    public MenuInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        cratePlayer = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        login.setFont(new java.awt.Font("Chinese Takeaway", 2, 36)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        login.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        login.setOpaque(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        add(login);
        login.setBounds(440, 320, 300, 60);

        cratePlayer.setFont(new java.awt.Font("Chinese Takeaway", 2, 36)); // NOI18N
        cratePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/createPlayer.png"))); // NOI18N
        cratePlayer.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cratePlayer.setOpaque(false);
        cratePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cratePlayerActionPerformed(evt);
            }
        });
        add(cratePlayer);
        cratePlayer.setBounds(440, 420, 300, 63);

        exit.setFont(new java.awt.Font("Chinese Takeaway", 2, 36)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        exit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exit.setOpaque(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        add(exit);
        exit.setBounds(440, 520, 300, 60);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainBackground.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       Menu.menu.setPanel(new LogIn());
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cratePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cratePlayerActionPerformed
        Menu.menu.setPanel(new CreatePlayer());
    }//GEN-LAST:event_cratePlayerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cratePlayer;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}