/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Leovavi
 */
public class MiCuenta extends javax.swing.JPanel {

    /**
     * Creates new form MiCuenta
     */
    public MiCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChangePassword = new javax.swing.JButton();
        btnConnectTwitter = new javax.swing.JButton();
        btnConnectFacebook = new javax.swing.JButton();
        btnDeleteAccount = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        puntosLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainLabel = new javax.swing.JLabel();

        setLayout(null);

        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/changePass.png"))); // NOI18N
        add(btnChangePassword);
        btnChangePassword.setBounds(370, 430, 200, 40);

        btnConnectTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conectTW.png"))); // NOI18N
        btnConnectTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectTwitterActionPerformed(evt);
            }
        });
        add(btnConnectTwitter);
        btnConnectTwitter.setBounds(370, 490, 200, 40);

        btnConnectFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conectFB.png"))); // NOI18N
        btnConnectFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectFacebookActionPerformed(evt);
            }
        });
        add(btnConnectFacebook);
        btnConnectFacebook.setBounds(620, 490, 200, 40);

        btnDeleteAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminarCuenta.png"))); // NOI18N
        add(btnDeleteAccount);
        btnDeleteAccount.setBounds(600, 430, 200, 40);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(933, 603, 200, 40);

        userLabel.setFont(new java.awt.Font("Chinese Takeaway", 2, 18)); // NOI18N
        userLabel.setText("Usuario: username");
        add(userLabel);
        userLabel.setBounds(440, 290, 280, 30);

        puntosLabel.setFont(new java.awt.Font("Chinese Takeaway", 2, 18)); // NOI18N
        puntosLabel.setText("Puntos: 0");
        add(puntosLabel);
        puntosLabel.setBounds(440, 330, 280, 30);

        jLabel1.setFont(new java.awt.Font("Chinese Takeaway", 2, 18)); // NOI18N
        jLabel1.setText("Fecha Creado: Fecha");
        add(jLabel1);
        jLabel1.setBounds(440, 370, 280, 30);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainBackground.png"))); // NOI18N
        add(MainLabel);
        MainLabel.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConnectTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectTwitterActionPerformed
        Menu.menu.showMessage("PROXIMAMENTE ESTARA DISPONIBLE");
    }//GEN-LAST:event_btnConnectTwitterActionPerformed

    private void btnConnectFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectFacebookActionPerformed
        Menu.menu.showMessage("PROXIMAMENTE ESTARA DISPONIBLE");
    }//GEN-LAST:event_btnConnectFacebookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnConnectFacebook;
    private javax.swing.JButton btnConnectTwitter;
    private javax.swing.JButton btnDeleteAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel puntosLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
