/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leovavi
 */
public class Ranking extends javax.swing.JPanel {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        initTable();
    }
    
    public void initTable(){
        try{
            String[] titles = {"Position", "Player", "Points"};
            rankingTable.setModel(new DefaultTableModel(Menu.xia.table(), titles));
        }catch(IOException e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        rankingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingTable = new javax.swing.JTable();
        MainLabel = new javax.swing.JLabel();

        setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(933, 603, 200, 40);

        rankingLabel.setFont(new java.awt.Font("Chinese Takeaway", 2, 24)); // NOI18N
        rankingLabel.setForeground(new java.awt.Color(153, 0, 0));
        rankingLabel.setText("Ranking");
        add(rankingLabel);
        rankingLabel.setBounds(520, 260, 90, 40);

        rankingTable.setFont(new java.awt.Font("Chinese Takeaway", 0, 14)); // NOI18N
        rankingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rankingTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(330, 320, 510, 230);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainBackground.png"))); // NOI18N
        add(MainLabel);
        MainLabel.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu.menu.setPanel(new Reportes());
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JTable rankingTable;
    // End of variables declaration//GEN-END:variables
}
