/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author Leovavi
 */
public class Reportes extends javax.swing.JPanel {
    Logs logs = new Logs();
    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRanking = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        MainLabel = new javax.swing.JLabel();

        setLayout(null);

        btnRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ranking.png"))); // NOI18N
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        add(btnRanking);
        btnRanking.setBounds(430, 330, 300, 60);

        btnLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logs.png"))); // NOI18N
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        add(btnLogs);
        btnLogs.setBounds(430, 430, 300, 60);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(933, 603, 200, 40);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MainBackground.png"))); // NOI18N
        add(MainLabel);
        MainLabel.setBounds(0, 0, 1150, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu.menu.setPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        Menu.menu.showMessage("PROXIMAMENTE ESTARA DISPONIBLE");
        //Menu.menu.setPanel(new Ranking());
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        if(!logs.dlm.isEmpty())
            Menu.menu.setPanel(new Logs());
        else
            Menu.menu.showMessage("No Logs Available");
    }//GEN-LAST:event_btnLogsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnRanking;
    // End of variables declaration//GEN-END:variables
}
